version: '3.9'


services:
  web:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/src/app/static
      - media_volume:/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - excursion_db
      - redis

  excursion_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

  redis:
    image: redis:latest
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
  static_volume:
  media_volume:
