version: '3.9'


services:
  web:
    build: ./
    command: bash -c "python /usr/src/app/manage.py migrate && python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - /home/james/Desktop/Excursion_site/ex_site:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - /home/james/Desktop/Excursion_site/ex_site/.env.dev
    depends_on:
      - db


  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - /home/james/Desktop/Excursion_site/ex_site/.env.dev
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=excursion_db

volumes:
  postgres_data:
